make script POSIX compatible

diff --git a/components/rule-watcher/rule-watcher b/components/rule-watcher/rule-watcher
--- a/components/rule-watcher/rule-watcher
+++ b/components/rule-watcher/rule-watcher
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 apk add --no-cache  curl gettext inotify-tools;
 
@@ -15,7 +15,7 @@ substituteENV() {
 
 triggerReload() {
     echo "triggering thanos rule reload..."
-    if [[ $(curl -s -w "%{http_code}" -X POST localhost:10902/-/reload) != 200 ]]; then 
+    if [ "$(curl -s -w "%{http_code}" -X POST localhost:10902/-/reload)" != 200 ]; then 
         echo "error reloading alert rules"
     fi
 }
@@ -36,11 +36,15 @@ triggerReload
 #     /var/thanos/rule-templates/ DELETE test1.yaml
 #     /var/thanos/rule-templates/ DELETE,ISDIR ..2024_07_29_13_27_29.567810463
 
-echo "starting rules-watcher...";
+echo "starting rule-watcher...";
 inotifywait -m -e delete --format '%e %w %f' "$templatedRulesPath" |\
 while read -r event path name; do
     echo "processing... $event $path $name";
-    if [[ "$event" != "DELETE,ISDIR" || ! "$name" =~ ^\.{2}.+\.[[:digit:]]+$ ]]; then
+    if [ "$event" != "DELETE,ISDIR" ]; then
+        continue
+    fi
+    # match name to '..2024_07_29_13_27_29.567810463' format
+    if ! expr "X$name" : 'X\.\.20[0-9][0-9]_[0-9_]\+\.[0-9]\+$' > /dev/null; then
         continue
     fi
 
@@ -51,4 +55,4 @@ while read -r event path name; do
     substituteENV
     triggerReload
 done;
-echo "error rules-watcher stopped";
+echo "error rule-watcher stopped";
