Kill the inotifywait proc in cleanup (#107)
* Kill the inotifywait proc in cleanup

* Better logging

diff --git a/components/rule-watcher/rule-watcher b/components/rule-watcher/rule-watcher
--- a/components/rule-watcher/rule-watcher
+++ b/components/rule-watcher/rule-watcher
@@ -2,7 +2,14 @@
 
 apk add --no-cache  curl gettext inotify-tools;
 
-trap 'echo TERM signal received exiting...; exit' SIGINT SIGTERM
+cleanup() {
+    echo "stopping..."
+    kill "$INOTIFY_PID"
+    echo "stopped inotifywait"
+    exit
+}
+
+trap cleanup SIGINT SIGTERM
 
 substituteENV() {
     echo "substituting the values of environment variables in rules..."
@@ -41,7 +48,7 @@ triggerReload
 #     /var/thanos/rule-templates/ DELETE test1.yaml
 #     /var/thanos/rule-templates/ DELETE,ISDIR ..2024_07_29_13_27_29.567810463
 
-echo "starting rule-watcher...";
+echo "starting rule-watcher..."
 inotifywait -m -r -e delete --format '%e %w %f' "$TEMPLATED_RULES_PATH" |\
 while read -r event path name; do
     echo "processing... $event $path $name";
@@ -59,5 +66,10 @@ while read -r event path name; do
     
     substituteENV
     triggerReload
-done;
-echo "error rule-watcher stopped";
+done &
+
+INOTIFY_PID=$!
+
+wait $INOTIFY_PID
+
+echo "error: rule-watcher stopped"
